apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: trends-analyzer
  namespace: trends-analyzer
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: trends-analyzer
    spec:
      containers:
      - name: trends-analyzer
        image: cezkuj/trends-analyzer:0.1.4
        args: ["-n", "$(NEWSAPIKEY)", "-p", "$(DB_PASSWORD)", "-t", "$(TWITTERAPIKEY)", "-ve"]
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trends-secret
              key: dbPassword
        - name: NEWSAPIKEY
          valueFrom:
            secretKeyRef:
              name: trends-secret
              key: newsAPIKey
        - name: TWITTERAPIKEY
          valueFrom:
            secretKeyRef:
              name: trends-secret
              key: twitterAPIKey
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/gcloud/credentials.json
        ports:
        - containerPort: 8000
          name: http-api
        volumeMounts:
        - name: gcloud-vol
          mountPath: /secrets/gcloud/
          readOnly: true
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=future-infusion-202918:europe-west3:trends=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        securityContext:
          runAsUser: 2  
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
      volumes:
      - name: gcloud-vol
        secret:
          secretName: gcloud-creds
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: trends-analyzer
  namespace: trends-analyzer
spec:
  ports:
  - port: 8000
  selector:
    app: trends-analyzer
