apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: trends-analyzer
  namespace: trends-analyzer
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: trends-analyzer
    spec:
      containers:
      - name: trends-analyzer
        image: cezkuj/trends-analyzer:0.0.1-CLOUD
        args: ["-o", "($DB_HOST):3306", "-d", "trends", "-n", "$NEWSAPIKEY", "-p", "trends_analyzer", "-t", "$TWITTERAPIKEY", "-u", "ta"]
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: trends-secret
              key: dbHost
        - name: NEWSAPIKEY
          valueFrom:
            secretKeyRef:
              name: trends-secret
              key: newsAPIKey
        - name: TWITTERAPIKEY
          valueFrom:
            secretKeyRef:
              name: trends-secret
              key: twitterAPIKey
        ports:
        - containerPort: 8000
          name: http-api
---
apiVersion: v1
kind: Service
metadata:
  name: trends-analyzer
  namespace: trends-analyzer
spec:
  ports:
  - port: 8000
  selector:
    app: trends-analyzer
