apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: trends-analyzer
  namespace: trends-analyzer
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: trends-analyzer
    spec:
      containers:
      - name: trends-analyzer
        image: cezkuj/trends-analyzer:0.1.3
        args: ["-o", "$(DB_HOST)", "-n", "$(NEWSAPIKEY)", "-p", "trends_analyzer", "-t", "$(TWITTERAPIKEY)"]
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: trends-secret
              key: dbHost
        - name: NEWSAPIKEY
          valueFrom:
            secretKeyRef:
              name: trends-secret
              key: newsAPIKey
        - name: TWITTERAPIKEY
          valueFrom:
            secretKeyRef:
              name: trends-secret
              key: twitterAPIKey
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "~/.gcloud.json"
        ports:
        - containerPort: 8000
          name: http-api
        volumeMounts:
        - name: gcloud-vol
          mountPath: "~/.gcloud.json"
          readOnly: true
      volumes:
      - name: gcloud-vol
        secret:
          secretName: gcloud-creds
---
apiVersion: v1
kind: Service
metadata:
  name: trends-analyzer
  namespace: trends-analyzer
spec:
  ports:
  - port: 8000
  selector:
    app: trends-analyzer
