apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: trends-analyzer
  namespace: trends-analyzer
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: trends-analyzer-ui
          servicePort: 80
